SmarAPDChallenge/Controllers/RoomsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using SmarAPDChallenge.Services;
using SmarAPDChallenge.ViewModels.Rooms;

namespace SmarAPDChallenge.Controllers
{
    [Authorize]
    public class RoomsController : Controller
    {
        private ScheduleService _sheduleService;

        public RoomsController(ScheduleService scheduleService)
        {
            _sheduleService = scheduleService;
        }

        [HttpGet]
        public IActionResult Index(string name = null)
        {
            var data = GetItems(name);
            return View(data);
        }

        [HttpGet]
        public IActionResult CreateModal()
        {
            var data = new RoomCreateViewModel();
            return PartialView(data);
        }

        [HttpPost]
        public IActionResult Create(RoomCreateViewModel room)
        {
            _sheduleService.CreateRoom(room);
            var data = GetItems(null);
            return PartialView("ItemsTable", data);
        }

        [HttpDelete]
        public IActionResult Delete(int id)
        {
            var hasSchedule = _sheduleService.GetRoomSchedules(id).ToList();

            if (hasSchedule.Count() == 0)
            {
                _sheduleService.DeleteRoom(id);
                var data = GetItems(null);
                return PartialView("ItemsTable", data);
            }
            else
            {
                return BadRequest("There are room appointments!");
            }
        }

        private RoomListViewModel GetItems(string name = null)
        {
            var data = new RoomListViewModel();

            data.items = _sheduleService.GetRooms(name).Select(x => new RoomListItemViewModel()
            {
                Id = x.Id,
                Name = x.Name
            }).ToList();

            return data;
        }
    }
}

SmarAPDChallenge/Views/Shared/_Layout.cshtml
@using Microsoft.AspNetCore.Identity
@inject SignInManager<IdentityUser> SignInManager
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - SmarAPDChallenge</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/lib/datetimepicker/jquery.datetimepicker.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">SmarAPDChallenge</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <partial name="_LoginPartial" />
                    <ul class="navbar-nav flex-grow-1">
                        @if (SignInManager.IsSignedIn(User))
                        {
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Rooms" asp-action="Index">Rooms</a>
                            </li>
                        }
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2020 - SmarAPDChallenge
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/jquery-validation/dist/jquery.validate.js"></script>
    <script src="~/lib/datetimepicker/build/jquery.datetimepicker.full.min.js"></script>
    <script src="~/lib/bootstrap-notify/bootstrap-notify.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @RenderSection("Scripts", required: false)
</body>
</html>